from models.location import *
from models.depth import *
import repositories.location_repository as location_repository
import repositories.depth_repository as depth_repository

# location = location_repository.select_by_id(7)
# print(location.name)
# print(location.region)
# print(location.id)

depth = depth_repository.select_by_location_id(7)
print(depth.value)
print(depth.temperature)
print(depth.location.name)
print(depth.id)





# Altnabreac_1 = Location("Altnabreac_1", "Caithness")
# location_repository.save(Altnabreac_1)
# Altnabreac_2 = Location("Altnabreac_2", "Caithness")
# location_repository.save(Altnabreac_2)
# Altnabreac_3 = Location("Altnabreac_3", "Caithness")
# location_repository.save(Altnabreac_3)
# LothbegNo1 = Location("LothbegNo1", "Caithness")
# location_repository.save(LothbegNo1)
# Bennachie = Location("Bennachie", "East_Grampians")
# location_repository.save(Bennachie)
# MtBattock  = Location("MtBattock", "East_Grampians")
# location_repository.save(MtBattock)
# Ballater = Location("Ballater", "East_Grampians")
# location_repository.save(Ballater)
# Rashiehill  = Location("Rashiehill", "West_Midland_Valley")
# location_repository.save(Rashiehill)
# Clachie_Bridge  = Location("Clachie_Bridge", "West_Midland_Valley")
# location_repository.save(Clachie_Bridge)
# Salsburgh   = Location("Salsburgh", "West_Midland_Valley")
# location_repository.save(Salsburgh)
# Hallside  = Location("Hallside", "West_Midland_Valley")
# location_repository.save(Hallside)
# Grangemouth  = Location("Grangemouth", "West_Midland_Valley")
# location_repository.save(Grangemouth)
# South_Balgray  = Location("South_Balgray", "West_Midland_Valley")
# location_repository.save(South_Balgray)
# Blythswood  = Location("Blythswood", "West_Midland_Valley")
# location_repository.save(Blythswood)
# Douglas_Colliery  = Location("Douglas_Colliery", "West_Midland_Valley")
# location_repository.save(Douglas_Colliery)
# Solsgirth_Colliery  = Location("Solsgirth_Colliery", "West_Midland_Valley")
# location_repository.save(Solsgirth_Colliery)
# Bogside_Colliery  = Location("Bogside_Colliery", "West_Midland_Valley")
# location_repository.save(Bogside_Colliery)
# Highhouse_Colliery  = Location("Highhouse_Colliery", "West_Midland_Valley")
# location_repository.save(Highhouse_Colliery)
# Barony_Colliery  = Location("Barony_Colliery", "West_Midland_Valley")
# location_repository.save(Barony_Colliery)
# Killoch_Colliery  = Location("Killoch_Colliery", "West_Midland_Valley")
# location_repository.save(Killoch_Colliery)
# Polkemmet_Colliery  = Location("Polkemmet_Colliery", "West_Midland_Valley")
# location_repository.save(Polkemmet_Colliery)
# Eggerton = Location("Eggerton", "West_Midland_Valley")
# location_repository.save(Eggerton)
# Tillicoultry  = Location("Tillicoultry", "West_Midland_Valley")
# location_repository.save(Tillicoultry)
# Tullibody  = Location("Tullibody", "West_Midland_Valley")
# location_repository.save(Tullibody)
# Cartlove  = Location("Cartlove", "West_Midland_Valley")
# location_repository.save(Cartlove)
# Gartenkeir  = Location("Gartenkeir", "West_Midland_Valley")
# location_repository.save(Gartenkeir)
# Shannock_Hill  = Location("Shannock_Hill", "West_Midland_Valley")
# location_repository.save(Shannock_Hill)
# Pipersink  = Location("Pipersink", "West_Midland_Valley")
# location_repository.save(Pipersink)
# Glenochill  = Location("Glenochill", "West_Midland_Valley")
# location_repository.save(Glenochill)
# Queenslie  = Location("Queenslie", "West_Midland_Valley")
# location_repository.save(Queenslie)
# Slatehole = Location("Slatehole", "West_Midland_Valley")
# location_repository.save(Slatehole)
# Gallowknowe  = Location("Gallowknowe", "West_Midland_Valley")
# location_repository.save(Gallowknowe)
# Stoneyknowes  = Location("Stoneyknowes", "West_Midland_Valley")
# location_repository.save(Stoneyknowes)
# Craighead  = Location("Craighead", "West_Midland_Valley")
# location_repository.save(Craighead)
# Maryhill  = Location("Maryhill", "West_Midland_Valley")
# location_repository.save(Maryhill)
# Comrie = Location("Comrie", "West_Midland_Valley")
# location_repository.save(Comrie)
# Glenrothes  = Location("Glenrothes", "East_Midland_Valley")
# location_repository.save(Glenrothes)
# Balfour = Location("Balfour", "East_Midland_Valley")
# location_repository.save(Balfour)
# Windygates  = Location("Windygates", "East_Midland_Valley")
# location_repository.save(Windygates)
# Spilmersford  = Location("Spilmersford", "East_Midland_Valley")
# location_repository.save(Spilmersford)
# Midlothian  = Location("Midlothian", "East_Midland_Valley")
# location_repository.save(Midlothian)
# Birnieknowes  = Location("Birnieknowes", "East_Midland_Valley")
# location_repository.save(Birnieknowes)
# Marshall_Meadow  = Location("Marshall Meadow", "East_Midland_Valley")
# location_repository.save(Marshall_Meadow)
# Cousland_No5  = Location("Cousland No.5", "East_Midland_Valley")
# location_repository.save(Cousland_No5)
# Cousland_No6 = Location("Cousland No.6", "East_Midland_Valley")
# location_repository.save(Cousland_No6)
# Pumpherston  = Location("Pumpherston", "East_Midland_Valley")
# location_repository.save(Pumpherston)
# Lochead  = Location("Lochead", "East_Midland_Valley")
# location_repository.save(Lochead)
# Boreland  = Location("Boreland", "East_Midland_Valley")
# location_repository.save(Boreland)
# Mackies_Mill  = Location("Mackies Mill", "East_Midland_Valley")
# location_repository.save(Mackies_Mill)
# Thornton_Bridge = Location("Thornton Bridge", "East_Midland_Valley")
# location_repository.save(Thornton_Bridge)
# Thornton_Farm  = Location("Thornton Farm", "East_Midland_Valley")
# location_repository.save(Thornton_Farm)
# Eastfield = Location("Eastfield", "East_Midland_Valley")
# location_repository.save(Eastfield)
# Bilston_Glen_Colliery  = Location("Bilston Glen Colliery", "East_Midland_Valley")
# location_repository.save(Bilston_Glen_Colliery)
# Lady_Victoria_Colliery  = Location("Lady Victoria Colliery", "East_Midland_Valley")
# location_repository.save(Lady_Victoria_Colliery)
# Auchendinny  = Location("Auchendinny", "East_Midland_Valley")
# location_repository.save(Auchendinny)
# Wellsgreen  = Location("Wellsgreen", "East_Midland_Valley")
# location_repository.save(Wellsgreen)
# Livingston  = Location("Livingston", "East_Midland_Valley")
# location_repository.save(Livingston)
# Stewart  = Location("Stewart", "East_Midland_Valley")
# location_repository.save(Stewart)
# Frances  = Location("Frances", "East_Midland_Valley")
# location_repository.save(Frances)
# Monktonhall  = Location("Monktonhall", "East_Midland_Valley")
# location_repository.save(Monktonhall)
# Seafield = Location("Seafield", "East_Midland_Valley")
# location_repository.save(Seafield)
# Well_25_26_1 = Location("25_26_1", "East_Midland_Valley")
# location_repository.save(Well_25_26_1)
# Castle_Douglas  = Location("Castle Douglas", "Dumfries_and_Galloway")
# location_repository.save(Castle_Douglas)
# Archerbeck  = Location("Archerbeck", "Dumfries_and_Galloway")
# location_repository.save(Archerbeck)

# Depth_299 = Depth(299, 10.3, Altnabreac_1)
# depth_repository.save(Depth_299)
# Depth_301 = Depth(301, 8.8, Altnabreac_2)
# depth_repository.save(Depth_301)
# Depth_282 = Depth(282, 10.1, Altnabreac_3)
# depth_repository.save(Depth_282)
# Depth_736 = Depth(736, 40.6, LothbegNo1)
# depth_repository.save(Depth_736)
# Depth_294 = Depth(294, 14, Bennachie)
# depth_repository.save(Depth_294)
# Depth_263 = Depth(263, 14, MtBattock)
# depth_repository.save(Depth_263)
# Depth_296 = Depth(296, 14, Ballater)
# depth_repository.save(Depth_296)
# Depth_964 = Depth(964, 34.4, Rashiehill)
# depth_repository.save(Depth_964)
# Depth_300 = Depth(300, 13.2, Clachie_Bridge)
# depth_repository.save(Depth_300)
# Depth_883 = Depth(883, 30, Salsburgh)
# depth_repository.save(Depth_883)
# Depth_350 = Depth(350, 11.8, Hallside)
# depth_repository.save(Depth_350)
# Depth_1134 = Depth(1134, 45, Grangemouth)
# depth_repository.save(Depth_1134)
# Depth_160 = Depth(160, 15.3, South_Balgray)
# depth_repository.save(Depth_160)
# Depth_105 = Depth(105, 12, Blythswood)
# depth_repository.save(Depth_105)
# Depth_239 = Depth(239, 12.2, Douglas_Colliery)
# depth_repository.save(Depth_239)
# Depth_387 = Depth(387, 21.5, Solsgirth_Colliery)
# depth_repository.save(Depth_387)
# Depth_334 = Depth(334, 17, Bogside_Colliery)
# depth_repository.save(Depth_334)
# Depth_436 = Depth(436, 18, Highhouse_Colliery)
# depth_repository.save(Depth_436)
# Depth_411 = Depth(411, 17, Barony_Colliery)
# depth_repository.save(Depth_411)
# Depth_655 = Depth(655, 17, Killoch_Colliery)
# depth_repository.save(Depth_655)
# Depth_549 = Depth(549, 17, Polkemmet_Colliery)
# depth_repository.save(Depth_549)
# Depth_410 = Depth(410, 14, Eggerton)
# depth_repository.save(Depth_410)
# Depth_510 = Depth(510, 18, Tillicoultry)
# depth_repository.save(Depth_510)
# Depth_325 = Depth(325, 16, Tullibody)
# depth_repository.save(Depth_325)
# Depth_404 = Depth(404, 16.6, Cartlove)
# depth_repository.save(Depth_404)
# Depth_488 = Depth(488, 16, Gartenkeir)
# depth_repository.save(Depth_488)
# Depth_497 = Depth(497, 18, Shannock_Hill)
# depth_repository.save(Depth_497)
# Depth_408 = Depth(408, 20.2, Pipersink)
# depth_repository.save(Depth_408)
# Depth_628 = Depth(628, 30, Glenochill)
# depth_repository.save(Depth_628)
# Depth_691 = Depth(691, 36, Queenslie)
# depth_repository.save(Depth_691)
# Depth_1024 = Depth(1024, 40, Slatehole)
# depth_repository.save(Depth_1024)
# Depth_1261 = Depth(1261, 37.5, Gallowknowe)
# depth_repository.save(Depth_1261)
# Depth_277 = Depth(277, 13.5, Stoneyknowes)
# depth_repository.save(Depth_277)
# Depth_977 = Depth(977, 35, Craighead)
# depth_repository.save(Depth_977)
# Depth_303 = Depth(303, 20, Maryhill)
# depth_repository.save(Depth_303)
# Depth_850 = Depth(850, 30, Comrie)
# depth_repository.save(Depth_850)
# Depth_279 = Depth(279, 14.4, Glenrothes)
# depth_repository.save(Depth_279)
# Depth_1205 = Depth(1205, 33.4, Balfour)
# depth_repository.save(Depth_1205)
# Depth_1298 = Depth(1298, 30, Windygates)
# depth_repository.save(Depth_1298)
# Depth_877 = Depth(877, 27.8, Spilmersford)
# depth_repository.save(Depth_877)
# Depth_747 = Depth(747, 37.8, Midlothian)
# depth_repository.save(Depth_747)
# Depth_372 = Depth(372, 23.9, Birnieknowes)
# depth_repository.save(Depth_372)
# Depth_227 = Depth(227, 11.5, Marshall_Meadow)
# depth_repository.save(Depth_227)
# Depth_585 = Depth(585, 17.8, Cousland_No5)
# depth_repository.save(Depth_585)
# Depth_582 = Depth(582, 23.9, Cousland_No6)
# depth_repository.save(Depth_582)
# Depth_1175 = Depth(1175, 36.7, Pumpherston)
# depth_repository.save(Depth_1175)
# Depth_1167 = Depth(1167, 30.4, Lochead)
# depth_repository.save(Depth_1167)
# Depth_1007 = Depth(1007, 29.8, Boreland)
# depth_repository.save(Depth_1007)
# Depth_960 = Depth(960, 33.3, Mackies_Mill)
# depth_repository.save(Depth_960)
# Depth_665 = Depth(665, 28, Thornton_Bridge)
# depth_repository.save(Depth_665)
# Depth_1055 = Depth(1055, 38, Thornton_Farm)
# depth_repository.save(Depth_1055)
# Depth_1028 = Depth(1028, 26, Eastfield)
# depth_repository.save(Depth_1028)
# Depth_670 = Depth(670, 15, Bilston_Glen_Colliery)
# depth_repository.save(Depth_670)
# Depth_768 = Depth(768, 18, Lady_Victoria_Colliery)
# depth_repository.save(Depth_768)
# Depth_459 = Depth(459, 18, Auchendinny)
# depth_repository.save(Depth_459)
# Depth_1485 = Depth(1485, 42.3, Wellsgreen)
# depth_repository.save(Depth_1485)
# Depth_640 = Depth(640, 27, Livingston)
# depth_repository.save(Depth_640)
# Depth_942 = Depth(942, 37.9, Stewart)
# depth_repository.save(Depth_942)
# Depth_841 = Depth(841, 29, Frances)
# depth_repository.save(Depth_841)
# Depth_866 = Depth(866, 25.5, Monktonhall)
# depth_repository.save(Depth_866)
# Depth_789 = Depth(789, 29, Seafield)
# depth_repository.save(Depth_789)
# Depth_2064 = Depth(2064, 62, Well_25_26_1)
# depth_repository.save(Depth_2064)
# Depth_231 = Depth(231, 14.7, Castle_Douglas)
# depth_repository.save(Depth_231)
# Depth_1365 = Depth(1365, 61.2, Archerbeck)
# depth_repository.save(Depth_1365)


# depths = depth_repository.select_all()
# print(depths[15].value)
